In [1]:
import pandas as pd
import numpy as np

In [2]:
Dubizzle_path = r"C:\Users\bbuser\Desktop\DataScience-Brain-Bytes\Team_members\from_Hajer\data\dubizzle properties.csv"
Dubizzle_df = pd.read_csv(Dubizzle_path)
Dubizzle_df

,property_name,sale_price,prop_location,prop_area,prop_bathrooms,number_of_rooms
0,Furnished 3-Bedroom Lakefront Villa for Sale i...,"OMR 249,000","Salalah, Dhofar•",573 SQM,3,3
1,Luxury Apartment|Mouj Muscat |Freehold Ownersh...,"OMR 125,000","The Wave (Almouj), Muscat•",110 SQM,2,1
2,5 BR Spacious Villa in Azaiba Nearby Amenities,"OMR 197,000","Azaiba, Muscat•",600 SQM,4,5
3,Two Bedroom Seaview Apartment at Mandarin Orie...,"OMR 405,000","Qurum, Muscat•",131 SQM,3,2
4,Villa for Sale (Garden) - Sea View,"OMR 517,000","Yiti, Muscat•",506 SQM,6,4
...,...,...,...,...,...,...
4656,شقة مفروشة مميزة للبيع في الخوض السابعة,"OMR 38,900","Al Khoud, Muscat•",76 SQM,2,2
4657,أرض الطيب موقع جميل,"OMR 2,200","Ibri, Al Dhahirah•",600 SQM,not mentioned,not mentioned
4658,all types of interlock avaialble watsapp me 95...,"OMR 2,000","Al Rusayl, Muscat•",10 SQM,not mentioned,not mentioned
4659,فرصة ذهبية بمخطط الوطن المقابل للمعبيلة 8 بكاف...,"OMR 31,000","Barka, Al Batinah•",600 SQM,not mentioned,not mentioned
4660,ارض سكنيه للبيع ولايه بركاء\n\n*مربع الهرم الم...,"OMR 16,500","Barka, Al Batinah•",600 SQM,not mentioned,not mentioned

# **Exploraty data**

In [3]:
Dubizzle_df .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4661 entries, 0 to 4660
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    4661 non-null   object
 1   sale_price       4661 non-null   object
 2   prop_location    4661 non-null   object
 3   prop_area        4661 non-null   object
 4   prop_bathrooms   4661 non-null   object
 5   number_of_rooms  4661 non-null   object
dtypes: object(6)
memory usage: 218.6+ KB

In [4]:
Dubizzle_df.columns

Index(['property_name', 'sale_price', 'prop_location', 'prop_area',
       'prop_bathrooms', 'number_of_rooms'],
      dtype='object')

In [5]:
Dubizzle_df.describe()

,property_name,sale_price,prop_location,prop_area,prop_bathrooms,number_of_rooms
count,4661,4661,4661,4661,4661,4661
unique,3980,1052,79,1158,14,14
top,land for sell,"OMR 15,000","Al Amarat, Muscat•",600 SQM,not mentioned,not mentioned
freq,51,65,463,695,2267,2267

In [6]:
Dubizzle_df.shape

(4661, 6)

In [7]:
Dubizzle_df.head(10)

,property_name,sale_price,prop_location,prop_area,prop_bathrooms,number_of_rooms
0,Furnished 3-Bedroom Lakefront Villa for Sale i...,"OMR 249,000","Salalah, Dhofar•",573 SQM,3,3
1,Luxury Apartment|Mouj Muscat |Freehold Ownersh...,"OMR 125,000","The Wave (Almouj), Muscat•",110 SQM,2,1
2,5 BR Spacious Villa in Azaiba Nearby Amenities,"OMR 197,000","Azaiba, Muscat•",600 SQM,4,5
3,Two Bedroom Seaview Apartment at Mandarin Orie...,"OMR 405,000","Qurum, Muscat•",131 SQM,3,2
4,Villa for Sale (Garden) - Sea View,"OMR 517,000","Yiti, Muscat•",506 SQM,6,4
5,Exclusive Furnished 3-Bedroom Villa for Sale i...,"OMR 254,000","Salalah, Dhofar•",610 SQM,3,3
6,ارخص فیلا قید الانشاء | تقسیط | موج مسقط | 5 غ...,"OMR 573,300","The Wave (Almouj), Muscat•",549 SQM,6,5
7,"Luxury Sea View Apartment for Sale – Juman 2, ...","OMR 215,000","The Wave (Almouj), Muscat•",145 SQM,3,2
8,3 + 1 Fully Furnished Villa for Sale in Al Kho...,"OMR 150,000","Al Khoud, Muscat•",768 SQM,4,3
9,‎فيلا جديده راقيه للبيع في المعبيلة الثالثة,"OMR 120,000","Al Maabilah, Muscat•",408 SQM,6,6

In [8]:
Dubizzle_df.tail(10)

,property_name,sale_price,prop_location,prop_area,prop_bathrooms,number_of_rooms
4651,فيلا جديدة من اصل توين فيلا بالحيل ج مقابل مد...,"OMR 93,000","Al Hail, Muscat•",275 SQM,5,6
4652,ارض سكنية 600 متر العامرات جحلوت,"OMR 4,500","Al Amarat, Muscat•",600 SQM,not mentioned,not mentioned
4653,ارض سياحية واجهة بحريه اول خط ولاية قريات. ضباب,"OMR 250,000","Qurayyat, Muscat•","2,500 SQM",not mentioned,not mentioned
4654,"2BHK + Service Room for Sale | Marsa Two, Al M...","OMR 145,000","The Wave (Almouj), Muscat•",140 SQM,2,2
4655,منزل طابقين للبيع بمنطقة روي,"OMR 90,000","Ruwi, Muscat•",167 SQM,not mentioned,not mentioned
4656,شقة مفروشة مميزة للبيع في الخوض السابعة,"OMR 38,900","Al Khoud, Muscat•",76 SQM,2,2
4657,أرض الطيب موقع جميل,"OMR 2,200","Ibri, Al Dhahirah•",600 SQM,not mentioned,not mentioned
4658,all types of interlock avaialble watsapp me 95...,"OMR 2,000","Al Rusayl, Muscat•",10 SQM,not mentioned,not mentioned
4659,فرصة ذهبية بمخطط الوطن المقابل للمعبيلة 8 بكاف...,"OMR 31,000","Barka, Al Batinah•",600 SQM,not mentioned,not mentioned
4660,ارض سكنيه للبيع ولايه بركاء\n\n*مربع الهرم الم...,"OMR 16,500","Barka, Al Batinah•",600 SQM,not mentioned,not mentioned

# **Check for null values/missing values**

In [9]:
Dubizzle_df.isnull().sum()

property_name      0
sale_price         0
prop_location      0
prop_area          0
prop_bathrooms     0
number_of_rooms    0
dtype: int64

# **Replace all "not mentioned" to be NaN**

In [10]:
Dubizzle_df.replace("not mentioned", np.nan, inplace=True)

In [11]:
Dubizzle_df.isnull().sum()

property_name         0
sale_price            0
prop_location         0
prop_area             0
prop_bathrooms     2267
number_of_rooms    2267
dtype: int64

# **Check for duplicates**

In [12]:
Dubizzle_df.duplicated().any()

np.True_

In [13]:
Dubizzle_df.duplicated().sum()

np.int64(378)

In [14]:
duplicates = Dubizzle_df[Dubizzle_df.duplicated()]
print(duplicates)

                                          property_name   sale_price  \
20    Exclusive Furnished 3-Bedroom Villa for Sale i...  OMR 254,000
21    ارخص فیلا قید الانشاء | تقسیط | موج مسقط | 5 غ...  OMR 573,300
22    Luxury Sea View Apartment for Sale – Juman 2, ...  OMR 215,000
23    3 + 1 Fully Furnished Villa for Sale in Al Kho...  OMR 150,000
24          ‎فيلا جديده راقيه للبيع في المعبيلة الثالثة  OMR 120,000
...                                                 ...          ...
3672                         ست فلل بوشر جال موقع ممتاز  OMR 390,000
4149                                         ارض تجاريه   OMR 15,000
4185                                         ارض تجاريه   OMR 15,000
4232                             سعر الفلل قابل للتفاوض   OMR 64,000
4368                           أرضين شبك في بركاء الدهس   OMR 23,500

                   prop_location  prop_area prop_bathrooms number_of_rooms
20              Salalah, Dhofar•    610 SQM              3               3
21    The Wave (Almouj), Muscat•    549 SQM              6               5
22    The Wave (Almouj), Muscat•    145 SQM              3               2
23             Al Khoud, Muscat•    768 SQM              4               3
24          Al Maabilah, Muscat•    408 SQM              6               6
...                          ...        ...            ...             ...
3672             Bosher, Muscat•  1,650 SQM            NaN             NaN
4149          Sohar, Al Batinah•    300 SQM            NaN             NaN
4185          Sohar, Al Batinah•    300 SQM            NaN             NaN
4232          Al Amarat, Muscat•    300 SQM              7               6
4368          Barka, Al Batinah•  1,200 SQM            NaN             NaN

[378 rows x 6 columns]

In [15]:
Dubizzle_df[Dubizzle_df.duplicated(subset=['prop_bathrooms', 'number_of_rooms'])]

,property_name,sale_price,prop_location,prop_area,prop_bathrooms,number_of_rooms
5,Exclusive Furnished 3-Bedroom Villa for Sale i...,"OMR 254,000","Salalah, Dhofar•",610 SQM,3,3
7,"Luxury Sea View Apartment for Sale – Juman 2, ...","OMR 215,000","The Wave (Almouj), Muscat•",145 SQM,3,2
11,أرض للبيع او الاستثمار بناية سكنيه تجارية,"OMR 250,000","Al Buraimi, Al Buraimi•",547 SQM,NaN,NaN
12,ارض للبيع سكني تجاري في غلاء - Land for sale i...,OMR 500,"Ghala, Muscat•","2,934 SQM",NaN,NaN
14,الأرض للبيع مساحه ٢١٠٨ م,"OMR 50,000","Barka, Al Batinah•","2,108 SQM",NaN,NaN
...,...,...,...,...,...,...
4656,شقة مفروشة مميزة للبيع في الخوض السابعة,"OMR 38,900","Al Khoud, Muscat•",76 SQM,2,2
4657,أرض الطيب موقع جميل,"OMR 2,200","Ibri, Al Dhahirah•",600 SQM,NaN,NaN
4658,all types of interlock avaialble watsapp me 95...,"OMR 2,000","Al Rusayl, Muscat•",10 SQM,NaN,NaN
4659,فرصة ذهبية بمخطط الوطن المقابل للمعبيلة 8 بكاف...,"OMR 31,000","Barka, Al Batinah•",600 SQM,NaN,NaN
4660,ارض سكنيه للبيع ولايه بركاء\n\n*مربع الهرم الم...,"OMR 16,500","Barka, Al Batinah•",600 SQM,NaN,NaN

In [16]:
Dubizzle_df.drop_duplicates(inplace=True)

In [17]:
Dubizzle_df.isnull().sum()

property_name         0
sale_price            0
prop_location         0
prop_area             0
prop_bathrooms     2183
number_of_rooms    2183
dtype: int64

# **Filling NaN data**

### **Filling for prop_bathrooms and number of rooms**

In [18]:
# I choose to fill this type of data with (Median) because it robust to outliers and good for room/bathroom counts
# To do this, I have first to convert the type of data from (Object) to (numeric)
# Convert to numeric (non-numeric values will become NaN automatically)
Dubizzle_df["prop_bathrooms"] = pd.to_numeric(Dubizzle_df["prop_bathrooms"], errors="coerce")
Dubizzle_df["number_of_rooms"] = pd.to_numeric(Dubizzle_df["number_of_rooms"], errors="coerce")

In [19]:
#Know I'll check of the conversion oocoured
Dubizzle_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4283 entries, 0 to 4660
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    4283 non-null   object
 1   sale_price       4283 non-null   object
 2   prop_location    4283 non-null   object
 3   prop_area        4283 non-null   object
 4   prop_bathrooms   2100 non-null   float64
 5   number_of_rooms  2047 non-null   float64
dtypes: float64(2), object(4)
memory usage: 234.2+ KB

In [20]:
#So now I can fill the missing values with the (Median)
Dubizzle_df["prop_bathrooms"].fillna(Dubizzle_df["prop_bathrooms"].median(), inplace=True)
Dubizzle_df["number_of_rooms"].fillna(Dubizzle_df["number_of_rooms"].median(), inplace=True)

C:\Users\bbuser\AppData\Local\Temp\ipykernel_24632\1168961233.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Dubizzle_df["prop_bathrooms"].fillna(Dubizzle_df["prop_bathrooms"].median(), inplace=True)
C:\Users\bbuser\AppData\Local\Temp\ipykernel_24632\1168961233.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Dubizzle_df["number_of_rooms"].fillna(Dubizzle_df["number_of_rooms"].median(), inplace=True)

In [21]:
#Check if I filled all NaN
Dubizzle_df.isnull().sum()

property_name      0
sale_price         0
prop_location      0
prop_area          0
prop_bathrooms     0
number_of_rooms    0
dtype: int64

In [22]:
Dubizzle_df

,property_name,sale_price,prop_location,prop_area,prop_bathrooms,number_of_rooms
0,Furnished 3-Bedroom Lakefront Villa for Sale i...,"OMR 249,000","Salalah, Dhofar•",573 SQM,3.0,3.0
1,Luxury Apartment|Mouj Muscat |Freehold Ownersh...,"OMR 125,000","The Wave (Almouj), Muscat•",110 SQM,2.0,1.0
2,5 BR Spacious Villa in Azaiba Nearby Amenities,"OMR 197,000","Azaiba, Muscat•",600 SQM,4.0,5.0
3,Two Bedroom Seaview Apartment at Mandarin Orie...,"OMR 405,000","Qurum, Muscat•",131 SQM,3.0,2.0
4,Villa for Sale (Garden) - Sea View,"OMR 517,000","Yiti, Muscat•",506 SQM,6.0,4.0
...,...,...,...,...,...,...
4656,شقة مفروشة مميزة للبيع في الخوض السابعة,"OMR 38,900","Al Khoud, Muscat•",76 SQM,2.0,2.0
4657,أرض الطيب موقع جميل,"OMR 2,200","Ibri, Al Dhahirah•",600 SQM,3.0,3.0
4658,all types of interlock avaialble watsapp me 95...,"OMR 2,000","Al Rusayl, Muscat•",10 SQM,3.0,3.0
4659,فرصة ذهبية بمخطط الوطن المقابل للمعبيلة 8 بكاف...,"OMR 31,000","Barka, Al Batinah•",600 SQM,3.0,3.0
4660,ارض سكنيه للبيع ولايه بركاء\n\n*مربع الهرم الم...,"OMR 16,500","Barka, Al Batinah•",600 SQM,3.0,3.0

In [23]:
#I'll remove the units from the columns for (sale_price) and (prop_area)
#Ensure the column is string
Dubizzle_df["sale_price"] = Dubizzle_df["sale_price"].astype(str)
#Extract the numeric part
Dubizzle_df["sale_price"] = Dubizzle_df["sale_price"].str.extract(r'(\d+\.?\d*)')[0]

#Convert to float
Dubizzle_df["sale_price"] = Dubizzle_df["sale_price"].astype(float)

#Convert from hundreds to thousands, then to int
Dubizzle_df["sale_price"] = (Dubizzle_df["sale_price"] * 1000).astype(int)

In [24]:
# Convert to string in case it's not
Dubizzle_df["prop_area"] = Dubizzle_df["prop_area"].astype(str)
#Extract the numeric part
Dubizzle_df["prop_area"] = Dubizzle_df["prop_area"].str.extract(r'(\d+\.?\d*)')[0]

#Convert to float
Dubizzle_df["prop_area"] = Dubizzle_df["prop_area"].astype(float)

#Convert from hundreds to thousands, then to int
Dubizzle_df["prop_area"] = (Dubizzle_df["prop_area"] * 1).astype(int)

In [25]:
Dubizzle_df

,property_name,sale_price,prop_location,prop_area,prop_bathrooms,number_of_rooms
0,Furnished 3-Bedroom Lakefront Villa for Sale i...,249000,"Salalah, Dhofar•",573,3.0,3.0
1,Luxury Apartment|Mouj Muscat |Freehold Ownersh...,125000,"The Wave (Almouj), Muscat•",110,2.0,1.0
2,5 BR Spacious Villa in Azaiba Nearby Amenities,197000,"Azaiba, Muscat•",600,4.0,5.0
3,Two Bedroom Seaview Apartment at Mandarin Orie...,405000,"Qurum, Muscat•",131,3.0,2.0
4,Villa for Sale (Garden) - Sea View,517000,"Yiti, Muscat•",506,6.0,4.0
...,...,...,...,...,...,...
4656,شقة مفروشة مميزة للبيع في الخوض السابعة,38000,"Al Khoud, Muscat•",76,2.0,2.0
4657,أرض الطيب موقع جميل,2000,"Ibri, Al Dhahirah•",600,3.0,3.0
4658,all types of interlock avaialble watsapp me 95...,2000,"Al Rusayl, Muscat•",10,3.0,3.0
4659,فرصة ذهبية بمخطط الوطن المقابل للمعبيلة 8 بكاف...,31000,"Barka, Al Batinah•",600,3.0,3.0
4660,ارض سكنيه للبيع ولايه بركاء\n\n*مربع الهرم الم...,16000,"Barka, Al Batinah•",600,3.0,3.0

In [26]:
#I'll rename the columns to add the units
Dubizzle_df.rename(columns={
    "sale_price": "sale_price OMR",
    "prop_area": "prop_area SqM"}, inplace=True)

In [27]:
Dubizzle_df

,property_name,sale_price OMR,prop_location,prop_area SqM,prop_bathrooms,number_of_rooms
0,Furnished 3-Bedroom Lakefront Villa for Sale i...,249000,"Salalah, Dhofar•",573,3.0,3.0
1,Luxury Apartment|Mouj Muscat |Freehold Ownersh...,125000,"The Wave (Almouj), Muscat•",110,2.0,1.0
2,5 BR Spacious Villa in Azaiba Nearby Amenities,197000,"Azaiba, Muscat•",600,4.0,5.0
3,Two Bedroom Seaview Apartment at Mandarin Orie...,405000,"Qurum, Muscat•",131,3.0,2.0
4,Villa for Sale (Garden) - Sea View,517000,"Yiti, Muscat•",506,6.0,4.0
...,...,...,...,...,...,...
4656,شقة مفروشة مميزة للبيع في الخوض السابعة,38000,"Al Khoud, Muscat•",76,2.0,2.0
4657,أرض الطيب موقع جميل,2000,"Ibri, Al Dhahirah•",600,3.0,3.0
4658,all types of interlock avaialble watsapp me 95...,2000,"Al Rusayl, Muscat•",10,3.0,3.0
4659,فرصة ذهبية بمخطط الوطن المقابل للمعبيلة 8 بكاف...,31000,"Barka, Al Batinah•",600,3.0,3.0
4660,ارض سكنيه للبيع ولايه بركاء\n\n*مربع الهرم الم...,16000,"Barka, Al Batinah•",600,3.0,3.0

In [28]:
Dubizzle_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4283 entries, 0 to 4660
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    4283 non-null   object
 1   sale_price OMR   4283 non-null   int64
 2   prop_location    4283 non-null   object
 3   prop_area SqM    4283 non-null   int64
 4   prop_bathrooms   4283 non-null   float64
 5   number_of_rooms  4283 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 234.2+ KB

In [29]:
#I'll convert float to int
Dubizzle_df['prop_area SqM'] = Dubizzle_df['prop_area SqM'].astype(int)
Dubizzle_df['prop_bathrooms'] = Dubizzle_df['prop_bathrooms'].astype(int)
Dubizzle_df['number_of_rooms'] = Dubizzle_df['number_of_rooms'].astype(int)

In [30]:
Dubizzle_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4283 entries, 0 to 4660
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    4283 non-null   object
 1   sale_price OMR   4283 non-null   int64
 2   prop_location    4283 non-null   object
 3   prop_area SqM    4283 non-null   int64
 4   prop_bathrooms   4283 non-null   int64
 5   number_of_rooms  4283 non-null   int64
dtypes: int64(4), object(2)
memory usage: 234.2+ KB

In [31]:
Dubizzle_df

,property_name,sale_price OMR,prop_location,prop_area SqM,prop_bathrooms,number_of_rooms
0,Furnished 3-Bedroom Lakefront Villa for Sale i...,249000,"Salalah, Dhofar•",573,3,3
1,Luxury Apartment|Mouj Muscat |Freehold Ownersh...,125000,"The Wave (Almouj), Muscat•",110,2,1
2,5 BR Spacious Villa in Azaiba Nearby Amenities,197000,"Azaiba, Muscat•",600,4,5
3,Two Bedroom Seaview Apartment at Mandarin Orie...,405000,"Qurum, Muscat•",131,3,2
4,Villa for Sale (Garden) - Sea View,517000,"Yiti, Muscat•",506,6,4
...,...,...,...,...,...,...
4656,شقة مفروشة مميزة للبيع في الخوض السابعة,38000,"Al Khoud, Muscat•",76,2,2
4657,أرض الطيب موقع جميل,2000,"Ibri, Al Dhahirah•",600,3,3
4658,all types of interlock avaialble watsapp me 95...,2000,"Al Rusayl, Muscat•",10,3,3
4659,فرصة ذهبية بمخطط الوطن المقابل للمعبيلة 8 بكاف...,31000,"Barka, Al Batinah•",600,3,3
4660,ارض سكنيه للبيع ولايه بركاء\n\n*مربع الهرم الم...,16000,"Barka, Al Batinah•",600,3,3

In [32]:
Dubizzle_df["Ad_Type"] = "For Sale"

In [33]:
Dubizzle_df

,property_name,sale_price OMR,prop_location,prop_area SqM,prop_bathrooms,number_of_rooms,Ad_Type
0,Furnished 3-Bedroom Lakefront Villa for Sale i...,249000,"Salalah, Dhofar•",573,3,3,For Sale
1,Luxury Apartment|Mouj Muscat |Freehold Ownersh...,125000,"The Wave (Almouj), Muscat•",110,2,1,For Sale
2,5 BR Spacious Villa in Azaiba Nearby Amenities,197000,"Azaiba, Muscat•",600,4,5,For Sale
3,Two Bedroom Seaview Apartment at Mandarin Orie...,405000,"Qurum, Muscat•",131,3,2,For Sale
4,Villa for Sale (Garden) - Sea View,517000,"Yiti, Muscat•",506,6,4,For Sale
...,...,...,...,...,...,...,...
4656,شقة مفروشة مميزة للبيع في الخوض السابعة,38000,"Al Khoud, Muscat•",76,2,2,For Sale
4657,أرض الطيب موقع جميل,2000,"Ibri, Al Dhahirah•",600,3,3,For Sale
4658,all types of interlock avaialble watsapp me 95...,2000,"Al Rusayl, Muscat•",10,3,3,For Sale
4659,فرصة ذهبية بمخطط الوطن المقابل للمعبيلة 8 بكاف...,31000,"Barka, Al Batinah•",600,3,3,For Sale
4660,ارض سكنيه للبيع ولايه بركاء\n\n*مربع الهرم الم...,16000,"Barka, Al Batinah•",600,3,3,For Sale

In [34]:
#Download file after changes
Dubizzle_df.to_csv("dubizzle_cleaned.csv", index=False)